In [1]:
#-*- coding:utf-8 -*-
import numpy as np
import numpy.random as rd
import pandas as pd

seed = 0

In [2]:
#S: 状態空間, |S|=N1
N1 = 3

#Y: イベントシンボル集合 |Y|=N2
Y = [0, 1]
print(Y)
N2 = len(Y)

[0, 1]


In [4]:
#y: 長さTのセッション
T = 3
rd.seed(0)
y = [0, 1, 0]
print(y)

[0, 1, 0]


### Baum-Welch

In [5]:
#E-Step: (α, β, τ, τ'の推定)
#初期化
gamma = np.array([1/N1 for _ in range(N1)]) #等確率とする
alpha = np.zeros((T, N1))
beta = np.zeros((T, N1))
A = np.array([[1, 7, 2],
              [2, 1, 7],
              [7, 2, 1]]) / 10

B = np.array([[9, 1],
              [6, 4],
              [1, 9]]) / 10

In [6]:
A

array([[0.1, 0.7, 0.2],
       [0.2, 0.1, 0.7],
       [0.7, 0.2, 0.1]])

In [7]:
B

array([[0.9, 0.1],
       [0.6, 0.4],
       [0.1, 0.9]])

In [8]:
gamma

array([0.33333333, 0.33333333, 0.33333333])

In [9]:
#αについて(forward型推定)
#Step1: 初期化
alpha[0] = gamma * B[:, y[0]]

#Step2: 再帰的計算
for t in range(T-1):
    for j in range(N1):
        alpha[t+1, j] = np.sum(alpha[t] * A[:, j]) * B[j, y[t+1]]

In [10]:
#βについて(backward推定)
#Step1: 初期化
beta[-1] = 1

#Step2: 再帰的計算
for t in range(T-1)[::-1]:
    for i in range(N1):
        beta[t, i] = np.sum(A[i] * B[:, y[t+1]] * beta[t+1])

In [11]:
#τについて


In [13]:
np.sum(alpha[-1])

0.17337333333333335

In [14]:
beta

array([[0.2289, 0.5018, 0.1303],
       [0.53  , 0.31  , 0.76  ],
       [1.    , 1.    , 1.    ]])

In [18]:
np.sum(gamma * B[:,y[0]] * beta[0])

0.17337333333333332